name: 'VKS: set context'
description: 'get kubeconfig file for your VKS cluster'
author: 'Ventus Cloud'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
