name: VKS Test
on:
  push:
    branches:
    - master
jobs:  
  build:
    runs-on: ubuntu-latest
    
    steps:
 
    - name: Install kubectl
      uses: azure/k8s-actions/setup-kubectl@master
      with:
        version: '1.14.0' # default is latest stable
      id: install

    - name: Setup python
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64' 

    - name: VKS test
      uses: olegchorny/javascript-actions@master
      with: 
        url: ${{ secrets.URL }}
        project: ${{ secrets.PROJECT }}
        domain: ${{ secrets.DOMAIN }}
        user: ${{ secrets.USER }}
        userdomain: ${{ secrets.USERDOMAIN }}
        password: ${{ secrets.PASSWORD }}
        cluster: ${{ secrets.CLUSTER }}
