name: VKS Test
on:
  push:
    branches:
    - master
jobs:  
  context:
    runs-on: ubuntu-latest
    
    steps:
 
#    - name: Install kubectl
#      uses: azure/k8s-actions/setup-kubectl@master
#      with:
#  version: 'v1.14.0' # default is latest stable
#      id: install

    - name: Setup python
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64' 

    - name: VKS test
      uses: ventus-ag/vks-action@master
      with: 
        authUrl: ${{ secrets.URL }}
        projectName: ${{ secrets.PROJECT }}
        domainName: ${{ secrets.DOMAIN }}
        userName: ${{ secrets.USER }}
        userDomainName: ${{ secrets.USERDOMAIN }}
        userPassword: ${{ secrets.PASSWORD }}
        clusterName: ${{ secrets.CLUSTER }}
